### ISSUE TITLE
ERROR: Playlist Player: skipping unplayable

### ISSUE THREAD

**Issue by puglial** [NeverWise/plugin.video.dplay#23]
@cttynul sto usando l'ultima versione del tuo fork, credo che abbiano cambiato di nuovo API
```
2019-11-02 10:33:09.431 T:7952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\Luca\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 187, in <module>
                                                dplay = Dplay()
                                              File "C:\Users\Luca\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 53, in __init__
                                                result = self._getStream(self._params['value'])
                                              File "C:\Users\Luca\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 83, in _getStream
                                                response = self._getResponseJson('https://dplay-south-prod.disco-api.com/playback/videoPlaybackInfo/{0}'.format(video_id), True)
                                              File "C:\Users\Luca\AppData\Roaming\Kodi\addons\plugin.video.dplay\default.py", line 134, in _getResponseJson
                                                if 'Data' in response.body:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
2019-11-02 10:33:09.469 T:18068   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.dplay/?
```

**Comment by NeverWise** [comment]
A me non sembra ci siano problemi con le API. Attento che potresti aver selezionato uno dei programmi a pagamento. Per questo motivo hai l'errore.
