### ISSUE TITLE
Python dependency could not be satisfied 

### ISSUE THREAD

**Issue by Fabio8G2** [NeverWise/plugin.video.dplay#28]
Hi, on tvbox (with Android 7) and kodi 19.0, install error: 'the dependency on xbmc.python version 2.14.0 could not be satisfied'.
Any fix?
Thanks!

**Comment by NeverWise** [comment]
This repository is very poorly maintained due to the time I have available so I don't know if I will release a fix.

**Comment by Fabio8G2** [comment]
This sound so sad! Can i help you? I was wondering: if is a dipendency issue, install the correct python version could be the solution?
Or the python version used for the addon is not supported by kodi 19.0? This means that the entire plug-in must be write using the supported python version?

**Comment by NeverWise** [comment]
I don't know what is the real reason but if I were to attempt a fix the first thing I would do is increase the version of the xbmc.python library. The addon code should be fine and compatible.

**Comment by Fabio8G2** [comment]
Ok! I'll try to update the python library! Thanks!

**Comment by Fabio8G2** [comment]
i was wondering: if i have the latest version of kodi (19.1) whith the latest xbmc.python version, why an higher version (2.14.0) is needed?

**Comment by Fabio8G2** [comment]
Ok now i'm a bit confused. Kodi 19.1 cames with python 3 which is newer than the version needed for the addon...
it seems that the python version used for the addon is not supported by kodi 19.1. Is it possible?

**Comment by Fabio8G2** [comment]
according with the changelog file, the addon is compatibile with python 3 e 2 since the 1.0.7 version...
what if i would change the import instruction in the addon.xml? Could work?

**Comment by Fabio8G2** [comment]
I edited both addon.xml files in script.module.neverwise and in plugin.video.dplay changing the requested xbmc.python to the version 3.0.0.
The script.module is now installed, but the installation of dplay plugin fail due to an invalid structure.

**Comment by Fabio8G2** [comment]
I finally installed dplay but it doesn't work....Here is the log:

2021-09-25 16:12:01.702 T:16608    INFO <general>: JSONRPC Server: Disconnection detected
2021-09-25 16:12:02.171 T:16608    INFO <general>: JSONRPC Server: New connection added
2021-09-25 16:12:03.208 T:16565   ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-09-25 16:12:03.242 T:17034    INFO <general>: initializing python engine.
2021-09-25 16:12:07.465 T:17034   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'xbmcgui.ListItem' object has no attribute 'setThumbnailImage'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dplay/default.py", line 281, in <module>
                                                       dplay = Dplay()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dplay/default.py", line 61, in __init__
                                                       self._addItem(title, { 'at' : self._access_token, 'action' : 's', 'value' : show['id'] }, icon , fanart, desc)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dplay/default.py", line 271, in _addItem
                                                       li = nw.createListItem(title, thumbnailImage = logo, fanart = fanart, streamtype = 'video', infolabels = { 'title' : title, 'plot' : plot }, duration = duration, isPlayable = isPlayable, contextMenu = contextMenu)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.neverwise/lib/neverwise.py", line 178, in createListItem
                                                       li.setThumbnailImage(thumbnailImage)
                                                   AttributeError: 'xbmcgui.ListItem' object has no attribute 'setThumbnailImage'
                                                   -->End of Python script error report<--
                                                   
2021-09-25 16:12:08.628 T:17034    INFO <general>: Python interpreter stopped
2021-09-25 16:12:08.644 T:17032   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.dplay/
2021-09-25 16:12:08.653 T:16565   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dplay/) failed

Don't know if it can help but the addon hasn't the Dplay thumbnail icon.

Any ideas?

**Comment by NeverWise** [comment]
At this point I think it's possible that the add-on code is not compatible with the newer versions of Kodi.
https://codedocs.xyz/AlwinEsch/kodi/python_v19.html

**Comment by Fabio8G2** [comment]
Removed iconImage and thumbnailImage. Use **setArt()**.
Syntax: # setArt(values)
listitem.setArt({ 'poster': 'poster.png', 'banner' : 'banner.png' })

the removed method was colled in script.module, right?!

**Comment by Fabio8G2** [comment]
OK...it works, but no audio...
I changed the old method with the new one in neverwise.py....then i reinstalled both, script.module and dplay addon.
On open it goes straith to the list of contents, there's no menus or search function. But i can see programs list and i can play but without audio...
The log seems fine...

**Comment by Fabio8G2** [comment]
i found something in the log:
2021-09-29 17:02:09.338 T:9991     INFO <general>: initializing python engine.
2021-09-29 17:02:10.611 T:9938     INFO <general>: Python interpreter stopped
2021-09-29 17:02:28.923 T:9991     INFO <general>: Skipped 4 duplicate messages..
2021-09-29 17:02:28.923 T:9991     INFO <general>: CPythonInvoker(21, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dplay/default.py): script successfully run
2021-09-29 17:02:29.787 T:9991     INFO <general>: Python interpreter stopped
2021-09-29 17:02:34.257 T:10016    INFO <general>: initializing python engine.
2021-09-29 17:02:37.777 T:10016    INFO <general>: CPythonInvoker(22, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dplay/default.py): script successfully run
2021-09-29 17:02:38.622 T:10016    INFO <general>: Python interpreter stopped
2021-09-29 17:02:40.619 T:10021    INFO <general>: initializing python engine.
2021-09-29 17:02:47.017 T:10021    INFO <general>: CPythonInvoker(23, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dplay/default.py): script successfully run
2021-09-29 17:02:47.077 T:9380     INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.dplay/?at=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZHBsYXlpdDo1NmFmNTAyYi0wZmJlLTRlZjItODI2MS1jMTVhYmNjYjY2MGIiLCJqdGkiOiJ0b2tlbi0zZDAwYTViYS05ZjcxLTQ4ZWQtYjUwMS00MTY3MzU1NjJkNzQiLCJhbm9ueW1vdXMiOnRydWUsImlhdCI6MTYzMjkyNzczNX0.ZUmD1As38C_RRqQxvTVcFx9U95l3fef6kaY5e0Qww-A&action=v&value=37003
2021-09-29 17:02:47.332 T:10029    INFO <general>: Creating InputStream
2021-09-29 17:02:47.687 T:10029    INFO <general>: Creating Demuxer
2021-09-29 17:02:48.138 T:10021    INFO <general>: Python interpreter stopped
2021-09-29 17:02:50.132 T:10029    INFO <general>: Opening stream: 0 source: 256
2021-09-29 17:02:50.133 T:10029    INFO <general>: Creating video codec with codec id: 27
2021-09-29 17:02:50.134 T:10029    INFO <general>: CBitstreamConverter::Open Invalid avcC
2021-09-29 17:02:50.135 T:10029    INFO <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.hevc.decoder.awesome
2021-09-29 17:02:50.135 T:10029    INFO <general>: CDVDVideoCodecAndroidMediaCodec::Open Testing codec:OMX.amlogic.avc.decoder.awesome
2021-09-29 17:02:50.280 T:10029    INFO <general>: CDVDVideoCodecAndroidMediaCodec:: Open Android MediaCodec OMX.amlogic.avc.decoder.awesome
2021-09-29 17:02:50.281 T:10029    INFO <general>: Creating video thread
2021-09-29 17:02:50.283 T:10040    INFO <general>: running thread: video_thread
2021-09-29 17:02:50.513 T:9380     INFO <general>: Instancing CRendererMediaCodecSurface
**2021-09-29 17:02:50.514 T:9380     INFO <general>: CRendererMediaCodecSurface::Configure
2021-09-29 17:02:50.522 T:10029 WARNING <general>: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2021-09-29 17:02:55.322 T:9380     INFO <general>: CVideoPlayer::CloseFile()**
2021-09-29 17:02:55.324 T:9380     INFO <general>: VideoPlayer: waiting for threads to exit
2021-09-29 17:02:55.331 T:10029    INFO <general>: CVideoPlayer::OnExit()
2021-09-29 17:02:55.331 T:10029    INFO <general>: Closing stream player 2
2021-09-29 17:02:55.331 T:10029    INFO <general>: waiting for video thread to exit
2021-09-29 17:02:55.365 T:10040 WARNING <general>: OutputPicture - timeout waiting for buffer
2021-09-29 17:02:55.365 T:10040    INFO <general>: thread end: video_thread
2021-09-29 17:02:55.367 T:10029    INFO <general>: deleting video codec
2021-09-29 17:02:55.553 T:9380     INFO <general>: VideoPlayer: finished waiting
2021-09-29 17:02:55.553 T:9380     INFO <general>: CVideoPlayer::CloseFile()
2021-09-29 17:02:55.554 T:9380     INFO <general>: VideoPlayer: waiting for threads to exit
2021-09-29 17:02:55.554 T:9380     INFO <general>: VideoPlayer: finished waiting
2021-09-29 17:02:55.666 T:9380    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-09-29 17:02:55.719 T:10056    INFO <general>: initializing python engine.

**Comment by NeverWise** [comment]
For the audio problem I don't know how to help you.
You can try to find if there is another stream that works but if it isn't there I don't know how to help you. :-(

**Comment by Fabio8G2** [comment]
Scusa se cambio lingua, ma così mi viene meglio. Intanto grazie per le risposte. Hai almeno una vaga idea di quale potrebbe essere il problema? Il warning contenuto nel log potrebbe dare un'idea della causa oppure no?

**Comment by Fabio8G2** [comment]
Confermo che solo con dplay non ho audio su qualsiasi programma io scelga, inoltre ho notato un'altra cosa: andando nelle opzioni del player (stream adaptive) a riproduzioni avviata, nelle opzioni audio non ci sono tracce audio.
È possibile che la funzione getStream del file neverwise.py provveda ad ottenere solo le tracce video e non anche quelle audio?

**Comment by NeverWise** [comment]
Come ho già detto non so come aiutarti. Potrebbe essere che kodi non conosca il codec audio ma potrebbe anche essere che la traccia audio non sia presente nello stream (probabilmente perché le API non sono più quelle giuste).
Per quello che ne so io passo a kodi lo stream che leggo dalle API, non ho scritto codice che modifica lo stream.
